// Modules - Encapsulated Code (only share minimum)
const names = require ('./names')
const sayHi = require ('./util')
const data = require('./alternative-export')
require('./mindgrenade')
sayHi('suman')
sayHi(names.rojer)
